#namespce 
---
apiVersion: v1
kind: Namespace
metadata:
  name: jr-test
  labels:
    name: jr-ns

...
#pod with ns
---

apiVersion: v1
kind: Pod
metadata:
  namespace: jr-test
  name: jr-pod
  labels:
    name: jr-app
spec:
  containers:
  - name: jr-cont
    image: nginx
    ports:
    - containerPort: 80

...

#services with selector

---
apiVersion: v1
kind: Service
metadata:
  name: jr-test
spec:
  type: NodePort
  selector:
    app: jr-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000  # Specify the nodePort value here
    protocol: TCP

...
